server.port=${PORT:9090}

spring.datasource.url=jdbc:postgreql://dpg-d6qit8n5r7bs738i8t0g-a.oregon-postgres.render.com:5432/kalakartdb_riom
#spring.datasource.url=jdbc:postgresql://sruthi:2HQ7Nr3wLjfKpLjnfLfPTaxhbOx8e7OZ@dpg-d6qit8n5r7bs738i8t0g-a.oregon-postgres.render.com/
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sruthi
spring.datasource.password=2HQ7Nr3wLjfKpLjnfLfPTaxhbOx8e7OZ


#
#spring.datasource.url=jdbc:mysql://localhost:3306/kalakart
#spring.datasource.username=root
#spring.datasource.password=sruthi
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect